/*
 * tutorial/tut_5_2.c
 *
 * A single-threaded CPU + CUDA version of the AWACS simulation.
 * See comments in tut_5_1.c for details on the radar model.
 *
 * In this version, the CPU remains the simulation authority: the cimba event queue,
 * the simulated time, the target process behaviour, and the platform/orbit kinematics.
 * The GPU handles radar physics and determines detections.
 *
 * Key design decisions:
 *  - Terrain is born and lives on-device. The syntetic terrain map (~14 GB at
 *    1 arcsec over 1000 x 1000 nm) is generated by a kernel from a 512-entry
 *    permutation table in __constant__ memory, normalised by a reduction kernel,
 *    then bound to a cudaArray + cudaTextureObject. Only the permutation and
 *    scalars cross PCIe; the map never does. Elevation lookups go through the
 *    texture path for spatial-locality caching and clamped addressing.
 *
 *  - The host (CPU) calls the device (GPU) once per simulated second; the kernel
 *    internally sweeps n_dwells_per_step antenna positions (25 x 0.04 s). One
 *    launch and one host <-> device round trip per second of sim time, rather
 *    than per dwell amortizes the launch overhead by ~25x while keeping the
 *    per-dwell resolution in the simulation.
 *
 *  - The target state vectore is an array-of-structs for the behaviour code;
 *    the step gathers it into a contiguous pinned buffer laid out struct-of-arrays,
 *    uploaded with cudaMemcpyAsync for coalesced kernel access, and scatters
 *    results back the same way.
 *
 *  - Two-phase cull/compact pipeline. A triage kernel (one thread per target)
 *    integrates target kinematics for the step and applies screening vs radar
 *    horizon, elevation limits, nadir cone, and azimuth beam-gating, then
 *    atomicAdd-compacts the survivors into a work queue with their per-target
 *    dwell span. A ray-march kernel (one warp per queued target) then does the
 *    expensive work only for survivors: 32 lanes stride the LOS samples, a
 *    warp-collective vote resolves terrain shielding, and lane 0 runs the
 *    per-dwell detection draw. This separates the O(targets) cull
 *    (thread-per-item) from the O(survivors) march (warp-per-item) and keeps
 *    the heavy kernel's launch occupied with work that can actually produce a
 *    detection.
 *
 *  - Over-launch, don't read back. The ray-march grid is sized to the target
 *    count and guarded by `warp_id >= *queue_count`, trading a few idle warps
 *    for avoiding a device->host readback of the queue count to size the
 *    launch. The count stays on the device.
 *
 *  - Counter-based RNG. Per-target curand Philox state seeded from the trial
 *    seed makes the detection draws reproducible independent of launch
 *    configuration and warp scheduling -- a hard requirement for a Monte-Carlo
 *    study, and the reason RNG is keyed per target rather than per thread slot.
 *
 *  - Stream-ordered and async. All step work -- upload, triage, ray-march,
 *    download -- is enqueued on one stream and joined with a single
 *    stream-synchronise, so the only host stall per step is the dependent
 *    result read.
 *
 * The atomic compaction makes the queue order nondeterministic, but each
 * target's detection outcome depends only on its own state and pseudo-random
 * number generator stream, not on its queue slot, so per-trial results are
 * reproducible even though the intermediate ordering is not. Note that the
 * warp-per-target march carries the usual SIMT obligation: every warp-collective
 * in the march must be reached by all 32 lanes, which constrains how the
 * per-lane loop may exit.
 *
 * Copyright (c) Asbjørn M. Bonvik 2026.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <cimba.h>
#include <errno.h>
#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include <time.h>
#include <unistd.h>
#include "hdf5.h"

/* Shared C/CUDA data structures */
#include "tut_5_2.h"

/* Bit masks to distinguish between two types of user-defined logging messages. */
#define USER_ADMIN  0x00000001
#define USER_SENSOR 0x00000002
#define USER_TARGET 0x00000004
#define USER_ALL    0x0FFFFFFF

/* Radar targets spread uniformly about the map */
#define NUM_TARGETS 1000

/* Sensor update interval, seconds. There are multiple sensor dwells inside
 * each update interval. The GPU handles these, see tut_5_2.h */
const float sensor_step_s = 1.0f;
/* Sensor beam width, degrees - a very simplified antenna model */
const float sensor_beam_width_d = 1.4f;

/* Geometric conversion constants */
const double arcsec_to_meters = 30.87;
const double nm_to_meters = 1852.0;
const double feet_to_meters = 0.3048;
const double knots_to_ms = (1852.0 / 3600.0);
const double deg_to_rad = (2.0 * M_PI / 360.0);
const double rad_to_deg = (360.0 / (2.0 * M_PI));

/* WGS84 constants semi-major axis and eccentricity */
const double WGS84_A = 6378137.0;
const double WGS84_F = (1.0 / 298.257223563);
const double WGS84_E2 = (WGS84_F * (2.0 - WGS84_F));

/* For ParaView visualization */
const char *terrain_h5name = "terrain.vtkhdf";
const char *events_h5name = "events.vtkhdf";
/* Animation frame interval, seconds */
double frame_interval_s = 1.0;

struct target;
struct platform_state;
struct vtkhdf_handle;

struct vtkhdf_handle *vtkhdf_create(void);
void vtkhdf_destroy(struct vtkhdf_handle *h);

void events_vtkhdf_init(struct vtkhdf_handle *h, const char *filename, int n_targets);
void events_vtkhdf_close(const struct vtkhdf_handle *h);
void events_vtkhdf_append(struct vtkhdf_handle *h,
                   const struct target *targets,
                   const struct platform_state *awacs,
                   float sensor_dir,
                   float time_val);
void terrain_vtkhdf_write(const char *h5_filename, const float *map,
                          unsigned cols, unsigned rows,
                          float x_scale, float y_scale);

/* Utility function for user entertainment */
void progress_bar_update(unsigned int current, unsigned int total, time_t start_time);

/*******************************************************************************
 * The terrain model, altitudes in meters referred to a Cartesian plane touching
 * Earth at the reference position.
 */

/* Allocate memory for the terrain object */
struct terrain *terrain_create(void)
{
    struct terrain *tp = malloc(sizeof(struct terrain));
    cmb_assert_release(tp != NULL);

    tp->cols = 0;
    tp->rows = 0;
    tp->map = NULL;

    return tp;
}

void terrain_destroy(struct terrain *tp)
{
    cmb_assert_release(tp != NULL);
    cmb_assert_release(tp->map == NULL);

    cmi_free(tp);
}

/****************************************************************************
 * Radar targets spread over the map surface
 */

struct target {
    /* Active process parent class */
    struct cmb_process core;
    /* Inherent parameters */
    float rcs_m2[4];
    float state_time_s[4];
    float height_m;
    struct terrain *terrain;
    /* Instantaneous state at last update */
    enum target_mode mode;
    enum target_detect_state tds;
    float rcs_now_m2;
    float time_s;
    float x_m;
    float y_m;
    float alt_m;
    float dir_r;
    float vel_ms;
    /* Cumulative state */
    bool detected;
};

/*
 * Target cmb_process function
 */
void *target_proc(struct cmb_process *me, void *vctx)
{
    cmb_assert_release(me != NULL);
    cmb_assert_release(vctx != NULL);

    struct target *tgt = (struct target *)me;
    const struct terrain *terp = (struct terrain *)vctx;

    /* Pick a location at random */
    tgt->time_s = (float)cmb_time();
    tgt->x_m = (float)cmb_random_uniform(terp->x_min, terp->x_max);
    tgt->y_m = (float)cmb_random_uniform(terp->y_min, terp->y_max);
    /* Actual terrain altitude will be added on the GPU */
    tgt->alt_m = tgt->height_m;

    /* Set initial status probabilistically */
    const double ph = tgt->state_time_s[HIDING] / (tgt->state_time_s[HIDING] + tgt->state_time_s[DRIVING]);
    tgt->mode = (cmb_random_bernoulli(ph)) ? HIDING : DRIVING;
    tgt->tds = UNDETERMINED;

    while (true) {
        if (tgt->mode == HIDING) {
            /* Stay hidden for a random time */
            tgt->rcs_now_m2 = tgt->rcs_m2[HIDING];
            tgt->time_s = (float)cmb_time();
            tgt->vel_ms = 0.0f;
            cmb_process_hold(cmb_random_exponential(tgt->state_time_s[HIDING]));

            /* Unmask */
            tgt->mode = STAGING;
            tgt->rcs_now_m2 = tgt->rcs_m2[STAGING];
            tgt->time_s = (float)cmb_time();
            /* Erlang distribution, mean equal to tgt->state_time_s[STAGING] */
            unsigned t_k = 10u;
            double t_m = tgt->state_time_s[STAGING] / (float)t_k;
            cmb_process_hold(cmb_random_erlang(t_k, t_m));

            /* Shoot & scoot */
            tgt->mode = FIRING;
            tgt->rcs_now_m2 = tgt->rcs_m2[FIRING];
            tgt->time_s = (float)cmb_time();
            /* Erlang distribution, mean equal to tgt->state_time_s[FIRING] */
            t_k = 20u;
            t_m = tgt->state_time_s[FIRING] / (float)t_k;
            cmb_process_hold(cmb_random_erlang(t_k, t_m));
            tgt->mode = DRIVING;
        }
        else {
            /* Choose a direction and speed at random, move for a random time */
            cmb_assert_debug(tgt->mode == DRIVING);
            tgt->rcs_now_m2 = tgt->rcs_m2[DRIVING];
            tgt->dir_r = (float)cmb_random_uniform(0.0, 2.0 * M_PI);
            tgt->vel_ms = (float)cmb_random_uniform(5.0, 20.0);
            /* Erlang distribution, mean equal to tgt->state_time_s[DRIVING] */
            const unsigned t_k = 5u;
            const double t_m = tgt->state_time_s[DRIVING] / (float)t_k;
            tgt->time_s = (float)cmb_time();
            cmb_process_hold(cmb_random_erlang(t_k, t_m));
            tgt->mode = HIDING;
        }
    }
}

struct target *target_create(void)
{
    struct target *tgt = cmi_malloc(sizeof(struct target));

    return tgt;
}

void target_initialize(struct target *tgt,
                       const char *tgt_name,
                       const float height,
                       const float rcs_hiding,
                       const float rcs_staging,
                       const float rcs_firing,
                       const float rcs_driving,
                       const float dur_hiding,
                       const float dur_staging,
                       const float dur_firing,
                       const float dur_driving,
                       struct terrain *terp)
{
    cmb_assert_release(tgt != NULL);

    tgt->height_m = height;
    tgt->rcs_m2[0] = rcs_hiding;
    tgt->rcs_m2[1] = rcs_staging;
    tgt->rcs_m2[2] = rcs_firing;
    tgt->rcs_m2[3] = rcs_driving;
    tgt->state_time_s[0] = dur_hiding * 3600.0f;
    tgt->state_time_s[1] = dur_staging * 60.0f;
    tgt->state_time_s[2] = dur_firing;  /* In seconds already */
    tgt->state_time_s[3] = dur_driving * 3600.0f;
    tgt->terrain = terp;
    tgt->tds = UNDETERMINED;
    tgt->time_s = 0.0f;
    tgt->x_m = 0.0f;
    tgt->y_m = 0.0f;
    tgt->alt_m = 0.0f;
    tgt->dir_r = 0.0f;
    tgt->vel_ms = 0.0f;
    tgt->detected = false;

    cmb_process_initialize((struct cmb_process *)tgt, tgt_name, target_proc, terp, 0);
}

void target_terminate(struct target *tgt)
{
    cmb_assert_release(tgt != NULL);

    cmb_process_terminate((struct cmb_process *)tgt);
}

void target_destroy(struct target *tgt)
{
    cmb_assert_release(tgt != NULL);

    cmi_free(tgt);
}

/****************************************************************************
 * Geometry of the AWACS racetrack orbit
 */
struct racetrack {
    /* Parameters */
    float start_time;      /* Simulation time when first at anchor point */
    float anchor_lat_r;    /* Startpoint for hot leg, radians latitude */
    float anchor_lon_r;    /* Startpoint for hot leg, radians longitude */
    float orientation_r;   /* Direction of hot leg, radians from north  */
    float length_m;        /* Length of each leg in meters */
    float turn_radius_m;   /* In meters */
    float altitude_m;      /* In meters */
    float velocity_ms;     /* In meters per second */
    bool clockwise;        /* true for standard orbit, false for non-standard */

    /* Pre-calculated from parameters*/
    float turn_dist_m;     /* Length of turn perimeter, meters */
    float roll_angle_r;    /* Platform banking angle during turns, radians */
    float orbit_dist_m;    /* Length of entire orbit, meters */
    float orbit_time_s;    /* Duration of a full orbit, seconds */
    float side_multiplier; /* 1.0 for clockwise, -1.0 for anti-clockwise */
    float lat_r2m;         /* Local conversion radians to meters, latitude */
    float lon_r2m;         /* Local conversion radians to meters, longitude */
    float local_earth_radius_m;         /* Earth radius at the anchor point */
};

struct racetrack *racetrack_create(void)
{
    struct racetrack *rt = cmi_malloc(sizeof(struct racetrack));

    return rt;
}

void racetrack_initialize(struct racetrack *rt,
                          const float start_time,      /* Simulation time, hours */
                          const float anchor_lat,      /* Degrees, start of hot leg */
                          const float anchor_lon,      /* Degrees, start of hot leg */
                          const float orientation,     /* Degrees clockwise, north = 0 */
                          const float leg_length,      /* Nautical miles */
                          const float turn_radius,     /* Nautical miles */
                          const float flight_level,    /* FL; feet / 100 */
                          const float velocity,        /* Knots */
                          const bool clockwise)
{
    cmb_assert_release(rt != NULL);

    rt->start_time = 3600.0f * start_time;
    rt->anchor_lat_r = (float)(anchor_lat * deg_to_rad);
    rt->anchor_lon_r = (float)(anchor_lon * deg_to_rad);
    rt->orientation_r = (float)((90.0 - orientation) * deg_to_rad);
    rt->length_m = (float)(leg_length * nm_to_meters);
    rt->turn_radius_m = (float)(turn_radius * nm_to_meters);
    rt->altitude_m = (float)(flight_level * 100.0 * feet_to_meters);
    rt->velocity_ms = (float)(velocity * knots_to_ms);
    rt->clockwise = clockwise;

    rt->turn_dist_m = M_PI * rt->turn_radius_m;
    rt->orbit_dist_m = 2.0f * (rt->length_m + rt->turn_dist_m);
    rt->orbit_time_s = rt->orbit_dist_m / rt->velocity_ms;
    rt->side_multiplier = (rt->clockwise) ? -1.0f : 1.0f;

    /* WGS84 calculation of meters per degree at anchor point */
    const double sin_lat = sinf(rt->anchor_lat_r);
    const double cos_lat = cosf(rt->anchor_lat_r);

    const double common = 1.0 - (WGS84_E2 * sin_lat * sin_lat);
    const double sqrt_common = sqrt(common);

    /* Radius of curvature in the meridian (for north-south) */
    const double M = WGS84_A * (1.0 - WGS84_E2) / (common * sqrt_common);

    /* Radius of curvature in the prime vertical (for east-west) */
    const double N = WGS84_A / sqrt_common;

    /* Local radius of the WGS84 Earth ellipsoid at the anchor point */
    rt->local_earth_radius_m = (float)sqrt(M * N);

    /* For the headline printout we still apply the sea-level k. */
    const float k_sea = 1.0f / (1.0f
                                + rt->local_earth_radius_m
                                * -(atm_N0_units * 1.0e-6f / atm_scale_h_m));
    const float max_dist = sqrtf(2.0f * k_sea * rt->local_earth_radius_m * rt->altitude_m);
    printf("Radar horizon at %3.0f nautical miles (sea level target)\n",
            max_dist / nm_to_meters);

    /* Add flight altitude for a correct conversion rad => m at that level */
    rt->lat_r2m = (float)(M + rt->altitude_m);
    rt->lon_r2m = (float)((N + rt->altitude_m) * cos_lat);

    /* Calculate the roll angle for a coordinated turn */
    const double g = 9.80665;
    const double roll_mag = atan((rt->velocity_ms * rt->velocity_ms) / (rt->turn_radius_m * g));

    rt->roll_angle_r = (float)(roll_mag * -rt->side_multiplier);
    printf("Racetrack bank angle %3.1f deg\n", rt->roll_angle_r * rad_to_deg);
    printf("Racetrack orbit duration %4.0f seconds\n", rt->orbit_time_s);
}

void racetrack_terminate(struct racetrack *rt)
{
    cmb_unused(rt);
}

void racetrack_destroy(struct racetrack *rt)
{
    cmb_assert_release(rt != NULL);

    cmi_free(rt);
}

void racetrack_write_vtp(const struct racetrack *rt, const char *filename);

/******************************************************************************
 *  The sensor and the platform carrying it. The sensor is the active component,
 *  while the platform just recalculates its state whenever it is asked to.
 *  Internal units SI, i.e., meters, radians, seconds, radians.
 */
struct platform_state {
    float x;
    float y;
    float dir;
    float rol;
    float vel;
    float alt;
};

/*
 * Geometry update function called by the active sensor.
 */
static void platform_state_update(struct platform_state *state,
                                  const struct racetrack *rt,
                                  const double t)
{
    const double delta_t = t - rt->start_time;
    double d = fmod(delta_t * rt->velocity_ms, rt->orbit_dist_m);
    if (d < 0) {
        d += rt->orbit_dist_m;
    }

    /* What segment, and where in that segment? */
    double x_local, y_local, heading_local, roll_local;
    if (d < rt->length_m) {
        x_local = d;
        y_local = 0.0;
        heading_local = 0.0;
        roll_local = 0.0;
    }
    else if (d < rt->length_m + rt->turn_dist_m) {
        const double phi = (d - rt->length_m) / rt->turn_radius_m - M_PI / 2.0;
        x_local = rt->length_m + rt->turn_radius_m * cos(phi);
        y_local = rt->side_multiplier * rt->turn_radius_m * (1.0 + sin(phi));
        heading_local = (phi + M_PI / 2.0) * rt->side_multiplier;
        roll_local = rt->roll_angle_r;
    }
    else if (d < 2.0 * rt->length_m + rt->turn_dist_m) {
        const double d_seg = d - (rt->length_m + rt->turn_dist_m);
        x_local = rt->length_m - d_seg;
        y_local = rt->side_multiplier * 2.0 * rt->turn_radius_m;
        heading_local = M_PI;
        roll_local = 0.0f;
    }
    else {
        const double phi = (d - (2.0 * rt->length_m + rt->turn_dist_m)) / rt->turn_radius_m + M_PI / 2.0;
        x_local = rt->turn_radius_m * cos(phi);
        y_local = rt->side_multiplier * rt->turn_radius_m * (1.0 + sin(phi));
        heading_local = M_PI + (phi - M_PI / 2.0) * rt->side_multiplier;
        roll_local = rt->roll_angle_r;
    }

    /* Rotate to orbit orientation */
    const double rad_o = rt->orientation_r;
    const double cos_o = cos(rad_o);
    const double sin_o = sin(rad_o);

    /* Rotate local (x,y) by the orbit orientation */
    const double x_final = x_local * cos_o - y_local * sin_o;
    const double y_final = x_local * sin_o + y_local * cos_o;

    /* Apply cached WGS84 scales at anchor point */
    state->x = (float)x_final;
    state->y = (float)y_final;
    state->dir = (float)fmod(heading_local + rt->orientation_r + 2.0 * M_PI, 2.0 * M_PI);
    state->rol = (float)roll_local;
    state->vel = (float)rt->velocity_ms;
    state->alt = (float)rt->altitude_m;
}

/******************************************************************************
 * The sensor-carrying platform
 */
struct platform {
    struct platform_state state;
    struct sensor *radar;
    struct racetrack *orbit;
};

struct platform *platform_create(void)
{
    struct platform *pfp = cmi_malloc(sizeof(struct platform));

    return pfp;
}

void platform_initialize(struct platform *pfp)
{
    cmb_assert_release(pfp != NULL);
    pfp->state.x = 0.0f;
    pfp->state.y = 0.0f;
    pfp->state.dir = 0.0f;
    pfp->state.rol = 0.0f;
    pfp->state.vel = 0.0f;
    pfp->state.alt = 0.0f;
    pfp->radar = NULL;
    pfp->orbit = NULL;
}

void platform_terminate(struct platform *pfp)
{
    cmb_unused(pfp);
}

void platform_destroy(struct platform *pfp)
{
    cmb_assert_release(pfp != NULL);
    cmi_free(pfp);
}

/*
 * Calculate the state of the platform at current simulation time
 */
static void platform_update(struct platform *pfp)
{
    const struct racetrack *rt = pfp->orbit;
    const double t = cmb_time();
    struct platform_state *state = &(pfp->state);
    platform_state_update(state, rt, t);
}

/******************************************************************************
 * The active sensor process
 */
struct sensor {
    struct cmb_process proc;    /* Inheritance, not a pointer */
    struct platform *host;
    float cur_dir_r;
    float rpm;
    float elev_angle_min_r;
    float elev_angle_max_r;
    float beamwidth_r;          /* Antenna 3 dB beamwidth in azimuth, radians */
    float ref_range_m;          /* Reference range (meters) where SNR = 0 dB */
    float ref_rcs_m2;           /* Reference target cross-section (m^2) */
    struct radar_params radar;

    struct sensor_gpu_state gpu;    /* GPU detection pipeline state */
    /* Host-side scratch buffers used for target state before kernel launch */
    float *h_x, *h_y, *h_alt, *h_dir, *h_vel, *h_time, *h_height, *h_rcs;
    int   *h_mode;
    int   *h_tds_result;
    uint8_t *h_detected_result;

    struct vtkhdf_handle *hdf;
};

/*
 * The sensor cmb_process function
 */
void *sensor_proc(struct cmb_process *me, void *vctx)
{
    struct target *targets = vctx;
    struct sensor *senp = (struct sensor *)me;
    struct platform *host = senp->host;
    const struct racetrack *orbit = host->orbit;

    /* Total antenna rotation per host call (one simulated second). The
     * kernel divides this into n_dwells_per_step internal dwell steps. */
    const float rot_per_step = (float)(senp->rpm * (1.0f / 60.0f)
                                       * (2.0f * M_PI));
    const float rot_inc_per_dwell = rot_per_step / (float)n_dwells_per_step;

    while (true) {
        cmb_process_hold(1.0);

        /* Save the previous coordinates before updating */
        const float prev_hdg = host->state.dir;
        const float base_dir = senp->cur_dir_r;
        platform_update(host);

        /* Platform yaw between calls also rotates the beam relative to
         * the world frame. Distribute it evenly across the dwells. */
        const float ddir = host->state.dir - prev_hdg;
        const float effective_rot_inc = rot_inc_per_dwell
                                      + ddir / (float)n_dwells_per_step;

        /* Advance the antenna position by one full step's worth of
         * rotation, keeping cur_dir in [0, 2pi). */
        senp->cur_dir_r = base_dir + rot_per_step + ddir;
        while (senp->cur_dir_r >= 2.0f * (float)M_PI) {
            senp->cur_dir_r -= 2.0f * (float)M_PI;
        }
        while (senp->cur_dir_r <  0.0f) {
            senp->cur_dir_r += 2.0f * (float)M_PI;
        }

        /* --- Gather: pack target state into SoA --- */
        for (int i = 0; i < NUM_TARGETS; i++) {
            senp->h_x[i]      = targets[i].x_m;
            senp->h_y[i]      = targets[i].y_m;
            senp->h_alt[i]    = targets[i].alt_m;
            senp->h_dir[i]    = targets[i].dir_r;
            senp->h_vel[i]    = targets[i].vel_ms;
            senp->h_time[i]   = targets[i].time_s;
            senp->h_height[i] = targets[i].height_m;
            senp->h_rcs[i]    = targets[i].rcs_now_m2;
            senp->h_mode[i]   = (int)targets[i].mode;
        }

        /* --- GPU detection pipeline: 25 dwells in one kernel batch --- */
        sensor_gpu_step(&senp->gpu,
                        senp->h_x, senp->h_y, senp->h_alt,
                        senp->h_dir, senp->h_vel, senp->h_time,
                        senp->h_height, senp->h_rcs, senp->h_mode,
                        host->state.x, host->state.y, host->state.alt,
                        host->state.dir, host->state.rol,
                        base_dir, effective_rot_inc,
                        senp->beamwidth_r,
                        (float)cmb_time(),
                        orbit->local_earth_radius_m,
                        senp->elev_angle_min_r, senp->elev_angle_max_r,
                        senp->ref_range_m, senp->ref_rcs_m2,
                        &senp->radar,
                        senp->h_tds_result, senp->h_detected_result);

        /* --- Scatter: same as before --- */
        for (int i = 0; i < NUM_TARGETS; i++) {
            targets[i].x_m   = senp->h_x[i];
            targets[i].y_m   = senp->h_y[i];
            targets[i].alt_m = senp->h_alt[i];
            if (senp->h_vel[i] > 0.0f) {
                targets[i].time_s = (float)cmb_time();
            }
            targets[i].tds = (enum target_detect_state)senp->h_tds_result[i];
            if (senp->h_detected_result[i]) {
                targets[i].detected = true;
            }
        }
    }
}

struct sensor *sensor_create(void)
{
    struct sensor *senp = cmi_malloc(sizeof(struct sensor));

    return senp;
}

void sensor_initialize(struct sensor *senp, const char *name, const float rpm,
                       const float min_elev, const float max_elev,
                       const float ref_rng, const float ref_rcs,
                       struct platform *host, void *vctx,
                       const struct terrain *terp, const uint64_t seed)
{
    cmb_assert_release(senp != NULL);
    cmb_assert_release(host != NULL);

    senp->host = host;
    senp->cur_dir_r = (float)(M_PI / 2.0);
    senp->rpm = rpm;
    senp->elev_angle_min_r = min_elev;
    senp->elev_angle_max_r = max_elev;
    senp->beamwidth_r = (float)(sensor_beam_width_d * deg_to_rad);
    senp->ref_range_m = ref_rng * (float)nm_to_meters;
    senp->ref_rcs_m2 = ref_rcs;

    /* AN/APY-2-like reference values. Tutorial uses these as defaults;
     * a real scenario would tune them per radar mode. */
    senp->radar.range_res_m        = 150.0f;
    senp->radar.n_pulses_per_dwell = 12;
    senp->radar.cfar_n_ref         = 8;
    senp->radar.cfar_n_guard       = 1;
    senp->radar.cfar_alpha         = 5.62f;     /* Pfa ≈ 1e-6, N = 16 */
    senp->radar.noise_floor_norm   = 1.0f;       /* normalized; units arbitrary */
    senp->radar.cell_grid_n_range  = 4;
    senp->radar.cell_grid_n_cross  = 4;
    senp->radar.mdv_ms             = 4.0f;     /* ~4 m/s clutter-notch half-width */
    senp->radar.mti_improvement    = 1000.0f;  /* 30 dB clutter cancellation */
    senp->hdf = vtkhdf_create();
    events_vtkhdf_init(senp->hdf, events_h5name, NUM_TARGETS);

    const size_t sz = NUM_TARGETS * sizeof(float);
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_x, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_y, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_alt, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_dir, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_vel, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_time, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_height, sz, cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_rcs, sz, cudaHostAllocDefault));

    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_mode,
                          NUM_TARGETS * sizeof(int), cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_tds_result,
                              NUM_TARGETS * sizeof(int), cudaHostAllocDefault));
    CUDA_CHECK(cudaHostAlloc((void **)&senp->h_detected_result,
                              NUM_TARGETS * sizeof(uint8_t), cudaHostAllocDefault));

    sensor_gpu_init(&senp->gpu, NUM_TARGETS, seed, terp);

    cmb_process_initialize((struct cmb_process *)senp, name, sensor_proc, vctx, 0);
}

void sensor_terminate(struct sensor *senp)
{
    events_vtkhdf_close(senp->hdf);
    vtkhdf_destroy(senp->hdf);

    CUDA_CHECK(cudaFreeHost(senp->h_x));
    CUDA_CHECK(cudaFreeHost(senp->h_y));
    CUDA_CHECK(cudaFreeHost(senp->h_alt));
    CUDA_CHECK(cudaFreeHost(senp->h_dir));
    CUDA_CHECK(cudaFreeHost(senp->h_vel));
    CUDA_CHECK(cudaFreeHost(senp->h_time));
    CUDA_CHECK(cudaFreeHost(senp->h_height));
    CUDA_CHECK(cudaFreeHost(senp->h_rcs));
    CUDA_CHECK(cudaFreeHost(senp->h_mode));
    CUDA_CHECK(cudaFreeHost(senp->h_tds_result));
    CUDA_CHECK(cudaFreeHost(senp->h_detected_result));

    cmb_process_terminate((struct cmb_process *)senp);
}

void sensor_destroy(struct sensor *senp)
{
    cmi_free(senp);
}

/*****************************************************************************
 * Our simulated world consists of these entities.
 */
struct simulation {
    struct platform *AWACS;
    struct target *targets;
    struct cmb_process *HDF5_output;
};

/*
 * A single trial is defined by these parameters and generates these results.
 */
struct trial {
    struct terrain *terrain;
    double dur_s;
    uint64_t seed_used;
    unsigned num_found;
};

/*
 * Event to close down the simulation.
 */
void end_sim(void *subject, void *object)
{
    cmb_unused(object);

    const struct simulation *sim = subject;
    struct target *tgts = sim->targets;

    cmb_process_stop((struct cmb_process *)(sim->AWACS->radar), NULL);
    for (unsigned ui = 0; ui < NUM_TARGETS; ui++) {
        cmb_process_stop((struct cmb_process *)&tgts[ui], NULL);
    }

    cmb_process_stop(sim->HDF5_output, NULL);
}

const char *hhmmss_formatter(double t);

/*
 * A cmb_process to display a progress bar during the simulation
 */
void *ent_proc(struct cmb_process *me, void *vtp)
{
    cmb_unused(me);

    const time_t started = time(NULL);
    const unsigned ncycles = 100u;
    const double stime_start = cmb_time();
    const double stime_end = *(double *)vtp;
    const double stime_incr = (stime_end - stime_start) / ncycles;

    for (unsigned ui = 1; ui <= ncycles; ui++) {
        cmb_process_hold(stime_incr);
        progress_bar_update(ui, ncycles, started);
    }

    return NULL;
}

/*
 * A cmb_process to write snapshots to HDF5 output file
 */
void *out_proc(struct cmb_process *me, void *vtp)
{
    cmb_unused(me);
    const struct simulation *sim = (struct simulation *)vtp;
    struct target *tgts = sim->targets;        /* non-const: we write alt_m */
    struct platform *pfp = sim->AWACS;
    struct sensor *senp = pfp->radar;

    /* Opening frame at t=0. out_proc has the lowest priority (-1), so every
     * target_proc has already placed its target and the sensor (priority 0)
     * has not stepped yet: targets are positioned but unclassified. Prime
     * terrain-relative altitudes on the GPU so the first frame shows them on
     * the ground rather than at sea level, then emit the frame. */
    for (int i = 0; i < NUM_TARGETS; i++) {
        senp->h_x[i]      = tgts[i].x_m;
        senp->h_y[i]      = tgts[i].y_m;
        senp->h_height[i] = tgts[i].height_m;
    }

    /* Update them all in parallel */
    sensor_gpu_prime_altitudes(&senp->gpu, senp->h_x, senp->h_y,
                               senp->h_height, senp->h_alt);
    /* Copy the result */
    for (int i = 0; i < NUM_TARGETS; i++) {
        tgts[i].alt_m = senp->h_alt[i];
    }

    platform_update(pfp);
    events_vtkhdf_append(senp->hdf, tgts, &(pfp->state),
                         senp->cur_dir_r, (float)cmb_time());

    while (true) {
        cmb_process_hold(frame_interval_s);
        platform_update(pfp);
        events_vtkhdf_append(senp->hdf, tgts, &(pfp->state),
                             senp->cur_dir_r, (float)cmb_time());
    }
}

/*
 * The simulation driver function to execute one trial
 */
void run_trial(void *vtrl)
{
    cmb_assert_release(vtrl != NULL);
    struct trial *trl = vtrl;
    struct terrain *terp = trl->terrain;
    uint64_t seed = trl->seed_used;

    /* Set up our trial housekeeping, assuming random seed already set */
    printf("Initializing event queue\n");
    cmb_logger_flags_off(CMB_LOGGER_INFO);
    cmb_logger_flags_off(USER_ALL);
    cmb_event_queue_initialize(0.0);
    cmb_logger_timeformatter_set(hhmmss_formatter);

    /* Create and start the targets */
    printf("Initializing targets\n");
    struct simulation sim = {};
    sim.targets = cmi_calloc(NUM_TARGETS, sizeof(struct target));
    for (unsigned ui = 0; ui < NUM_TARGETS; ui++) {
        char namebuf[16];
        const size_t np = snprintf(namebuf, sizeof(namebuf), "Target_%d", ui);
        cmb_assert_release(np < sizeof(namebuf));
        const float height = 2.0f;      /* Meters above ground */
        const float rcs_hide = 5.0f;    /* Square meters */
        const float rcs_stage = 100.0f; /* Square meters */
        const float rcs_fire = 1000.0f; /* Square meters */
        const float rcs_drive = 50.0f;  /* Square meters */
        const float time_hide = 3.0f;   /* Hours */
        const float time_stage = 5.0f;  /* Minutes */
        const float time_fire = 30.0f;  /* Seconds */
        const float time_drive = 1.0f;  /* Hours */
        target_initialize(&sim.targets[ui], namebuf, height,
                          rcs_hide, rcs_stage, rcs_fire, rcs_drive,
                          time_hide, time_stage, time_fire, time_drive,
                          trl->terrain);

        cmb_process_start((struct cmb_process *)&sim.targets[ui]);
    }

    /* Create and start the AWACS */
    printf("Initializing racetrack pattern\n");
    struct racetrack *orbit = racetrack_create();
    const float start_time = 0.0f;      /* Hours */
    const float anchor_lat = 30.0f;     /* Degrees */
    const float anchor_lon = -10.0f;    /* Degrees */
    const float orientation = 0.0f;     /* Degrees, nautical */
    const float length = 50.0f;         /* Nautical miles */
    const float turn_radius = 10.0f;    /* Nautical miles */
    const float flight_level = 310.0f;  /* Flight level */
    const float velocity = 300.0f;      /* Knots */
    const bool clockwise = true;
    racetrack_initialize(orbit, start_time, anchor_lat, anchor_lon, orientation,
                         length, turn_radius, flight_level, velocity, clockwise);
    racetrack_write_vtp(orbit, "racetrack.vtp");

    printf("Initializing AWACS platform\n");
    struct platform *awacs = platform_create();
    sim.AWACS = awacs;
    platform_initialize(awacs);
    awacs->orbit = orbit;
    /* Set initial position and direction coordinates */
    platform_update(awacs);

    printf("Initializing radar\n");
    struct sensor *radar = sensor_create();
    sim.AWACS->radar = radar;
    const float rpm = 6.0f;
    const float max_elev = (float)(60.0 * deg_to_rad);
    const float min_elev = (float)(-20.0 * deg_to_rad);
    const float ref_range = 150.0f;     /* Nautical miles */
    const float ref_rcs = 1.0f;
    sensor_initialize(radar, "AN/APY-2", rpm, min_elev, max_elev,
                      ref_range, ref_rcs, awacs, sim.targets,
                      terp, seed);
    cmb_process_start((struct cmb_process *)radar);

    /* Schedule the simulation control events */
    printf("Scheduling end event\n");
    double t_end_s = trl->dur_s;
    cmb_event_schedule(end_sim, &sim, NULL, t_end_s, 0);

    /* Process to write output events */
    sim.HDF5_output = cmb_process_create();
    cmb_process_initialize(sim.HDF5_output, "HDF5_out", out_proc, &sim, -1);
    cmb_process_start(sim.HDF5_output);

    /* Process to show the progress bar */
    struct cmb_process *entertainment = cmb_process_create();
    cmb_process_initialize(entertainment, "Progress bar", ent_proc, &t_end_s, 0);
    cmb_process_start(entertainment);

    /* Run this trial */
    printf("\nRunning simulation for %4.1f simulated hours...\n", t_end_s/3600.0);
    fflush(stdout);
    cmb_event_queue_execute();

    trl->num_found = 0;
    for (unsigned ui = 0; ui < NUM_TARGETS; ui++) {
        if (sim.targets[ui].detected) {
            trl->num_found++;
        }
    }

    printf("\nFound %d targets of %d total, detection rate %4.1f %%\n",
            trl->num_found, NUM_TARGETS,
            100.0 * ((double)trl->num_found) / (double)(NUM_TARGETS));

    racetrack_terminate(orbit);
    racetrack_destroy(orbit);
    sensor_terminate(radar);
    sensor_destroy(radar);
    platform_terminate(awacs);
    platform_destroy(awacs);
    for (unsigned ui = 0; ui < NUM_TARGETS; ui++) {
        target_terminate(&sim.targets[ui]);
    }

    cmi_free(sim.targets);

    cmb_process_terminate(entertainment);
    cmb_process_destroy(entertainment);

    /* Final housekeeping to leave everything as we found it */
    cmb_event_queue_terminate();
    cmb_random_terminate();
}

/*
 * The minimal single-threaded main function
 */
int main(int argc, char **argv)
{
    bool timing_enabled = false;
    uint64_t seed = cmb_random_hwseed();
    double dur_h = 6.0;

    int opt;
    while ((opt = getopt(argc, argv, "d:s:t")) != -1) {
        switch (opt) {
            case 'd': {
                errno = 0;
                char *end = NULL;
                dur_h = strtod(optarg, &end);
                if (end == optarg        /* no digits consumed   */
                    || *end != '\0'      /* trailing garbage     */
                    || errno == ERANGE   /* overflow / underflow */
                    || dur_h <= 0.0) {   /* domain: hours > 0    */
                    fprintf(stderr, "Invalid -d value '%s' (want hours > 0)\n", optarg);
                    return EXIT_FAILURE;
                    }
                break;
            }

            case 's': {
                errno = 0;
                char *end = NULL;
                seed = strtoull(optarg, &end, 0);   /* base 0 => accepts 0x.., 0.. */
                if (end == optarg || *end != '\0' || errno == ERANGE || seed == 0u) {
                    fprintf(stderr, "Invalid -s value '%s' (want nonzero integer)\n", optarg);
                    return EXIT_FAILURE;
                }
                break;
            }

            case 't': {
                timing_enabled = true;
                break;
            }

            default: {
                fprintf(stderr, "Usage: %s [-d <hours>] [-s <seed>]\n", argv[0]);
                return EXIT_FAILURE;
            }
        }
    }

    /* Allocate and generate the terrain map to be used for several trials */
    const float fwidth_nm = 1000.0f;
    const float fheight_nm = 1000.0f;
    const float ref_lat = 30.0f;
    const float ref_lon = -10.0f;

    struct trial trl = {};
    const clock_t start_time = clock();

    printf("Initializing random generators\n");
    trl.seed_used = seed;
    cmb_random_initialize(trl.seed_used);

    struct terrain *tp = terrain_create();
    terrain_initialize(tp, fwidth_nm, fheight_nm, ref_lat, ref_lon, trl.seed_used);
    trl.terrain = tp;
    trl.dur_s = dur_h * 3600.0;

    const clock_t mid_time = clock();
    const double tergen_time = (double)(mid_time - start_time) / CLOCKS_PER_SEC;

    run_trial(&trl);

    if (timing_enabled) {
        const clock_t end_time = clock();
        const double simul_time = (double)(end_time - mid_time) / CLOCKS_PER_SEC;
        const double elapsed_time = (double)(end_time - start_time) / CLOCKS_PER_SEC;
        printf("\nTerrain generation took %g sec\n", tergen_time);
        printf("Simulation took %g sec\n", simul_time);
        printf("Total time %g sec\n", elapsed_time);
    }

    terrain_terminate(tp);
    terrain_destroy(tp);

    return 0;
}

/**************** Only I/O utility functions below this point ****************/

void progress_bar_update(const unsigned int current,
                         const unsigned int total,
                         const time_t start_time)
{
    const unsigned int bar_width = 40;
    const float progress = (float)current / (float)total;
    const unsigned int pos = (unsigned int)((float)bar_width * progress);

    const time_t now = time(NULL);
    const double elapsed = difftime(now, start_time);

    printf("\r[");
    for (unsigned int i = 0; i < bar_width; ++i) {
        if (i < pos) {
            printf("#");
        }
        else if (i == pos) {
            printf("=");
        }
        else {
            printf("-");
        }
    }

    /* Wait until 1 % progress to get a time estimate */
    printf("] %3d%% | ETA: ", (int)(progress * 100.0f));
    if (progress > 0.01f) {
        const int eta_sec = (int)(elapsed / progress - elapsed);
        printf("%02d:%02d", eta_sec / 60, eta_sec % 60);
    }
    else {
        printf("--:--");
    }

    fflush(stdout);
}

/* Internal time unit seconds, print in HHH:MM:SS.sss format */
#define FMTBUFLEN 20

const char *hhmmss_formatter(const double t)
{
    static CMB_THREAD_LOCAL char fmtbuf[FMTBUFLEN];

    double tmp = t;
    const unsigned h = (unsigned)(tmp / 3600.0);
    tmp -= (double)(h * 3600);
    const unsigned m = (unsigned)(tmp / 60.0);
    tmp -= (double)(m * 60.0);
    const double s = tmp;
    (void)snprintf(fmtbuf, FMTBUFLEN, "%03d:%02d:%04.1f", h, m, s);

    return fmtbuf;
}

struct vtkhdf_handle {
    hid_t file_id;
    int num_targets;
    unsigned long current_step;

    hid_t pts_dset;
    hid_t status_dset;
    hid_t rcs_dset;
    hid_t is_awacs_dset;
    hid_t awacs_dir_dset;
    hid_t sensor_dir_dset;

    hid_t step_vals_dset;
    hid_t step_pts_off_dset;
    hid_t step_cell_off_dset;
    hid_t step_part_off_dset;
    hid_t step_num_parts_dset;
    hid_t step_conn_id_off_dset;
};

struct vtkhdf_handle *vtkhdf_create(void)
{
    struct vtkhdf_handle *h = cmi_malloc(sizeof(struct vtkhdf_handle));

    return h;
}

void vtkhdf_destroy(struct vtkhdf_handle *h)
{
    cmi_free(h);
}

#define H5_CHECK(x) do { \
        hid_t __res = (x); \
        if (__res < 0) { \
            fprintf(stderr, "HDF5 Error at %s:%d (Function: %s)\n", __FILE__, __LINE__, #x); \
            exit(EXIT_FAILURE); \
        } \
    } while (0)

void write_attr_string(const hid_t loc_id, const char *const name, const char *const value)
{
    const hid_t type = H5Tcopy(H5T_C_S1);
    H5_CHECK(type);
    H5_CHECK(H5Tset_size(type, strlen(value)));
    H5_CHECK(H5Tset_strpad(type, H5T_STR_NULLPAD));

    const hid_t space = H5Screate(H5S_SCALAR);
    H5_CHECK(space);
    const hid_t attr = H5Acreate2(loc_id, name, type, space, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(attr);

    H5_CHECK(H5Awrite(attr, type, value));

    H5_CHECK(H5Aclose(attr));
    H5_CHECK(H5Sclose(space));
    H5_CHECK(H5Tclose(type));
}

void write_attr_int32_array(const hid_t loc_id, const char *const name, const int32_t *const values, const hsize_t count)
{
    const hid_t type = H5T_NATIVE_INT32;
    H5_CHECK(type);
    const hid_t space = H5Screate_simple(1, &count, NULL);
    H5_CHECK(space);
    const hid_t attr = H5Acreate2(loc_id, name, type, space, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(attr);

    H5_CHECK(H5Awrite(attr, type, values));

    H5_CHECK(H5Aclose(attr));
    H5_CHECK(H5Sclose(space));
}

void write_attr_int64_array(hid_t loc_id, const char *name,
                            const int64_t *values, hsize_t count)
{
    const hid_t space = H5Screate_simple(1, &count, NULL);
    H5_CHECK(space);
    const hid_t attr = H5Acreate2(loc_id, name, H5T_NATIVE_INT64,
                                  space, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(attr);
    H5_CHECK(H5Awrite(attr, H5T_NATIVE_INT64, values));
    H5_CHECK(H5Aclose(attr));
    H5_CHECK(H5Sclose(space));
}

void write_attr_double_array(const hid_t loc_id, const char *const name, const double *const values, const hsize_t count)
{
    const hid_t type = H5T_NATIVE_DOUBLE;
    H5_CHECK(type);
    const hid_t space = H5Screate_simple(1, &count, NULL);
    H5_CHECK(space);
    const hid_t attr = H5Acreate2(loc_id, name, type, space, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(attr);

    H5_CHECK(H5Awrite(attr, type, values));

    H5_CHECK(H5Aclose(attr));
    H5_CHECK(H5Sclose(space));
}

void terrain_vtkhdf_write(const char *const h5_filename,
                          const float *const map,
                          const uint32_t cols,        /* now: the resolution to write */
                          const uint32_t rows,
                          const float x_scale,        /* now: matches that resolution */
                          const float y_scale)
{
    /* No more internal decimation — caller has already done it if desired */

    const hid_t fapl = H5Pcreate(H5P_FILE_ACCESS);
    H5_CHECK(fapl);
    H5_CHECK(H5Pset_libver_bounds(fapl, H5F_LIBVER_LATEST, H5F_LIBVER_LATEST));
    const hid_t file_id = H5Fcreate(h5_filename, H5F_ACC_TRUNC, H5P_DEFAULT, fapl);
    H5_CHECK(file_id);
    H5Pclose(fapl);

    const hid_t root = H5Gcreate2(file_id, "VTKHDF", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(root);
    write_attr_string(root, "Type", "ImageData");
    const int64_t version[2] = { 2, 0 };
    write_attr_int64_array(root, "Version", version, 2);

    const int64_t extent[6] = {
        0, (int64_t)cols - 1,
        0, (int64_t)rows - 1,
        0, 0
    };

    write_attr_int64_array(root, "WholeExtent", extent, 6);

    const double total_x = (cols - 1) * (double)x_scale;
    const double total_y = (rows - 1) * (double)y_scale;
    const double origin[3] = { -(total_x / 2.0), -(total_y / 2.0), 0.0 };
    const double spacing[3] = { x_scale, y_scale, 1.0 };
    const double direction[9] = { 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 };

    write_attr_double_array(root, "Origin", origin, 3);
    write_attr_double_array(root, "Spacing", spacing, 3);
    write_attr_double_array(root, "Direction", direction, 9);

    const hid_t pd_group = H5Gcreate2(root, "PointData", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(pd_group);
    write_attr_string(pd_group, "Scalars", "Elevation");

    const hsize_t map_dims[2] = { (hsize_t)rows, (hsize_t)cols };
    const hid_t map_space = H5Screate_simple(2, map_dims, NULL);
    H5_CHECK(map_space);
    const hid_t map_dset = H5Dcreate2(pd_group, "Elevation", H5T_NATIVE_FLOAT,
                                      map_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(map_dset);
    H5_CHECK(H5Dwrite(map_dset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, map));

    H5_CHECK(H5Dclose(map_dset));
    H5_CHECK(H5Sclose(map_space));
    H5_CHECK(H5Gclose(pd_group));
    H5_CHECK(H5Gclose(root));
    H5_CHECK(H5Fclose(file_id));
}

/* Helper to create mandatory dummy groups for ParaView's strict reader */
static void write_dummy_topology_stepped(hid_t root, const char *name,
                                         unsigned long nsteps)
{
    const hid_t group = H5Gcreate2(root, name, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);

    int64_t *zeros = calloc(nsteps, sizeof(int64_t));

    const hsize_t dims[1]  = { nsteps };
    const hsize_t maxd[1]  = { H5S_UNLIMITED };
    const hsize_t chunk[1] = { 1 };

    const hid_t dcpl = H5Pcreate(H5P_DATASET_CREATE);
    H5Pset_chunk(dcpl, 1, chunk);

    const hid_t space = H5Screate_simple(1, dims, maxd);

    hid_t d = H5Dcreate2(group, "NumberOfCells",
                          H5T_NATIVE_INT64, space, H5P_DEFAULT, dcpl, H5P_DEFAULT);
    H5Dwrite(d, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, zeros);
    H5Dclose(d);

    d = H5Dcreate2(group, "NumberOfConnectivityIds",
                   H5T_NATIVE_INT64, space, H5P_DEFAULT, dcpl, H5P_DEFAULT);
    H5Dwrite(d, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, zeros);
    H5Dclose(d);

    d = H5Dcreate2(group, "Offsets",
                   H5T_NATIVE_INT64, space, H5P_DEFAULT, dcpl, H5P_DEFAULT);
    H5Dwrite(d, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, zeros);
    H5Dclose(d);

    const hsize_t one = 1;
    const hid_t conn_space = H5Screate_simple(1, &one, NULL);
    d = H5Dcreate2(group, "Connectivity",
                   H5T_NATIVE_INT64, conn_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5Dwrite(d, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, zeros);
    H5Dclose(d);
    H5Sclose(conn_space);

    H5Sclose(space);
    H5Pclose(dcpl);
    H5Gclose(group);

    free(zeros);
}

void events_vtkhdf_init(struct vtkhdf_handle *h, const char *filename, const int n_targets)
{
    h->num_targets = n_targets;
    h->current_step = 0;

    const int total_pts = n_targets + 1;

    h->file_id = H5Fcreate(filename, H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
    if (h->file_id < 0) {
        fprintf(stderr, "Failed to create HDF5 file: %s\n", filename);
        exit(EXIT_FAILURE);
    }

    const hid_t root = H5Gcreate2(h->file_id, "VTKHDF", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(root);
    write_attr_string(root, "Type", "PolyData");

    const int32_t version[2] = {2, 0};
    const hsize_t v_dim = 2;
    const hid_t v_space = H5Screate_simple(1, &v_dim, NULL);
    H5_CHECK(v_space);
    const hid_t v_attr = H5Acreate2(root, "Version", H5T_NATIVE_INT32, v_space, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(v_attr);
    H5_CHECK(H5Awrite(v_attr, H5T_NATIVE_INT32, version));
    H5_CHECK(H5Aclose(v_attr));
    H5_CHECK(H5Sclose(v_space));

    /* --- Static topology metadata --- */
    const hsize_t one_dim = 1;
    const hid_t static_space = H5Screate_simple(1, &one_dim, NULL);
    H5_CHECK(static_space);
    const int64_t static_count = (int64_t)total_pts;

    const hid_t d_np = H5Dcreate2(root, "NumberOfPoints", H5T_NATIVE_INT64, static_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(d_np);
    H5_CHECK(H5Dwrite(d_np, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, &static_count));
    H5_CHECK(H5Dclose(d_np));

    const hid_t d_nc = H5Dcreate2(root, "NumberOfCells", H5T_NATIVE_INT64, static_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(d_nc);
    H5_CHECK(H5Dwrite(d_nc, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, &static_count));
    H5_CHECK(H5Dclose(d_nc));

    const hid_t d_nci = H5Dcreate2(root, "NumberOfConnectivityIds", H5T_NATIVE_INT64, static_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(d_nci);
    H5_CHECK(H5Dwrite(d_nci, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, &static_count));
    H5_CHECK(H5Dclose(d_nci));

    /* --- Primary point data --- */
    const hsize_t p_dims[2] = {0, 3};
    const hsize_t p_max[2] = {H5S_UNLIMITED, 3};
    const hsize_t p_chunk[2] = {(hsize_t)total_pts, 3};
    const hid_t p_dcpl = H5Pcreate(H5P_DATASET_CREATE);
    H5_CHECK(p_dcpl);
    H5_CHECK(H5Pset_chunk(p_dcpl, 2, p_chunk));
    const hid_t p_space = H5Screate_simple(2, p_dims, p_max);
    H5_CHECK(p_space);
    H5_CHECK(h->pts_dset = H5Dcreate2(root, "Points", H5T_NATIVE_FLOAT, p_space, H5P_DEFAULT, p_dcpl, H5P_DEFAULT));
    const hid_t pd_group = H5Gcreate2(root, "PointData", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(pd_group);
    write_attr_string(pd_group, "Scalars", "Detection_Status");
    write_attr_string(pd_group, "Vectors", "Sensor_Direction");

    const hsize_t s_dims[1] = {0};
    const hsize_t s_max[1] = {H5S_UNLIMITED};
    const hsize_t s_chunk[1] = {(hsize_t)total_pts};
    const hid_t s_dcpl = H5Pcreate(H5P_DATASET_CREATE);
    H5_CHECK(s_dcpl);
    H5_CHECK(H5Pset_chunk(s_dcpl, 1, s_chunk));
    const hid_t s_space = H5Screate_simple(1, s_dims, s_max);
    H5_CHECK(s_space);

    H5_CHECK(h->status_dset = H5Dcreate2(pd_group, "Detection_Status", H5T_NATIVE_FLOAT, s_space, H5P_DEFAULT, s_dcpl, H5P_DEFAULT));
    H5_CHECK(h->is_awacs_dset = H5Dcreate2(pd_group, "Is_AWACS", H5T_NATIVE_FLOAT, s_space, H5P_DEFAULT, s_dcpl, H5P_DEFAULT));
    H5_CHECK(h->rcs_dset = H5Dcreate2(pd_group, "RCS", H5T_NATIVE_FLOAT, s_space, H5P_DEFAULT, s_dcpl, H5P_DEFAULT));
    H5_CHECK(h->awacs_dir_dset = H5Dcreate2(pd_group, "AWACS_Direction", H5T_NATIVE_FLOAT, p_space, H5P_DEFAULT, p_dcpl, H5P_DEFAULT));
    H5_CHECK(h->sensor_dir_dset = H5Dcreate2(pd_group, "Sensor_Direction", H5T_NATIVE_FLOAT, p_space, H5P_DEFAULT, p_dcpl, H5P_DEFAULT));

    H5_CHECK(H5Pclose(p_dcpl));
    H5_CHECK(H5Sclose(p_space));
    H5_CHECK(H5Pclose(s_dcpl));
    H5_CHECK(H5Sclose(s_space));

    /* --- Topology --- */
    const hid_t v_group = H5Gcreate2(root, "Vertices", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(v_group);
    const int64_t n_cells = (int64_t)total_pts;
    const int64_t n_conn = (int64_t)total_pts;
    int64_t *conn = malloc(total_pts * sizeof(int64_t));
    int64_t *off = malloc((total_pts + 1) * sizeof(int64_t));
    for (int i = 0; i < total_pts; i++) {
        conn[i] = i;
        off[i] = i;
    }
    off[total_pts] = total_pts;

    const hsize_t c_dim = (hsize_t)total_pts;
    const hid_t c_space = H5Screate_simple(1, &c_dim, NULL);
    H5_CHECK(c_space);

    const hsize_t o_dim = (hsize_t)total_pts + 1;
    const hid_t o_space = H5Screate_simple(1, &o_dim, NULL);
    H5_CHECK(o_space);

    const hid_t c_dset = H5Dcreate2(v_group, "Connectivity", H5T_NATIVE_INT64, c_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(c_dset);
    H5_CHECK(H5Dwrite(c_dset, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, conn));
    H5_CHECK(H5Dclose(c_dset));

    const hid_t o_dset = H5Dcreate2(v_group, "Offsets", H5T_NATIVE_INT64, o_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(o_dset);
    H5_CHECK(H5Dwrite(o_dset, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, off));
    H5_CHECK(H5Dclose(o_dset));

    const hid_t d_v_nc = H5Dcreate2(v_group, "NumberOfCells", H5T_NATIVE_INT64, static_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(d_v_nc);
    H5_CHECK(H5Dwrite(d_v_nc, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, &n_cells));
    H5_CHECK(H5Dclose(d_v_nc));

    const hid_t d_v_nci = H5Dcreate2(v_group, "NumberOfConnectivityIds", H5T_NATIVE_INT64, static_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(d_v_nci);
    H5_CHECK(H5Dwrite(d_v_nci, H5T_NATIVE_INT64, H5S_ALL, H5S_ALL, H5P_DEFAULT, &n_conn));
    H5_CHECK(H5Dclose(d_v_nci));

    free(conn);
    free(off);

    H5_CHECK(H5Sclose(o_space));
    H5_CHECK(H5Sclose(c_space));
    H5_CHECK(H5Sclose(static_space));
    H5_CHECK(H5Gclose(v_group));

    /* --- Temporal metadata --- */
    const hid_t st_group = H5Gcreate2(root, "Steps", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(st_group);
    const hsize_t t_dims[1] = {0};
    const hsize_t t_max[1] = {H5S_UNLIMITED};
    const hsize_t t_chunk[1] = {1};
    const hid_t t_dcpl = H5Pcreate(H5P_DATASET_CREATE);
    H5_CHECK(t_dcpl);
    H5_CHECK(H5Pset_chunk(t_dcpl, 1, t_chunk));
    const hid_t t_space = H5Screate_simple(1, t_dims, t_max);
    H5_CHECK(t_space);

    H5_CHECK(h->step_vals_dset = H5Dcreate2(st_group, "Values", H5T_NATIVE_FLOAT, t_space, H5P_DEFAULT, t_dcpl, H5P_DEFAULT));
    H5_CHECK(h->step_pts_off_dset = H5Dcreate2(st_group, "PointOffsets", H5T_NATIVE_INT64, t_space, H5P_DEFAULT, t_dcpl, H5P_DEFAULT));
    H5_CHECK(h->step_part_off_dset = H5Dcreate2(st_group, "PartOffsets", H5T_NATIVE_INT64, t_space, H5P_DEFAULT, t_dcpl, H5P_DEFAULT));
    H5_CHECK(h->step_num_parts_dset = H5Dcreate2(st_group, "NumberOfParts", H5T_NATIVE_INT64, t_space, H5P_DEFAULT, t_dcpl, H5P_DEFAULT));

    const hsize_t t2_dims[2]  = { 0, 5 };
    const hsize_t t2_max[2]   = { H5S_UNLIMITED, 5 };
    const hsize_t t2_chunk[2] = { 1, 5 };
    const hid_t t2_dcpl = H5Pcreate(H5P_DATASET_CREATE);
    H5_CHECK(t2_dcpl);
    H5_CHECK(H5Pset_chunk(t2_dcpl, 2, t2_chunk));
    const hid_t t2_space = H5Screate_simple(2, t2_dims, t2_max);
    H5_CHECK(t2_space);

    H5_CHECK(h->step_cell_off_dset    = H5Dcreate2(st_group, "CellOffsets",
                 H5T_NATIVE_INT64, t2_space, H5P_DEFAULT, t2_dcpl, H5P_DEFAULT));
    H5_CHECK(h->step_conn_id_off_dset = H5Dcreate2(st_group, "ConnectivityIdOffsets",
                 H5T_NATIVE_INT64, t2_space, H5P_DEFAULT, t2_dcpl, H5P_DEFAULT));

    H5_CHECK(H5Pclose(t2_dcpl));
    H5_CHECK(H5Sclose(t2_space));

    H5_CHECK(H5Pclose(t_dcpl));
    H5_CHECK(H5Sclose(t_space));
    H5_CHECK(H5Gclose(st_group));
    H5_CHECK(H5Gclose(pd_group));
    H5_CHECK(H5Gclose(root));
    H5_CHECK(H5Fflush(h->file_id, H5F_SCOPE_GLOBAL));
}

void events_vtkhdf_append(struct vtkhdf_handle *h, const struct target *targets, const struct platform_state *awacs, const float sensor_dir, const float time_val)
{
    const int n = h->num_targets;
    const int total_pts = n + 1;
    const hsize_t n_steps = h->current_step + 1;

    /* --- Extend datasets --- */
    const hsize_t p_ext[2] = { n_steps * total_pts, 3 };
    H5_CHECK(H5Dset_extent(h->pts_dset, p_ext));
    H5_CHECK(H5Dset_extent(h->awacs_dir_dset, p_ext));
    H5_CHECK(H5Dset_extent(h->sensor_dir_dset, p_ext));

    const hsize_t s_ext[1] = { n_steps * total_pts };
    H5_CHECK(H5Dset_extent(h->status_dset, s_ext));
    H5_CHECK(H5Dset_extent(h->rcs_dset, s_ext));
    H5_CHECK(H5Dset_extent(h->is_awacs_dset, s_ext));

    const hsize_t t_ext[1] = { n_steps };
    H5_CHECK(H5Dset_extent(h->step_vals_dset, t_ext));
    H5_CHECK(H5Dset_extent(h->step_pts_off_dset, t_ext));
    H5_CHECK(H5Dset_extent(h->step_part_off_dset, t_ext));
    H5_CHECK(H5Dset_extent(h->step_num_parts_dset, t_ext));

    const hsize_t t2_ext[2] = { n_steps, 5 };
    H5_CHECK(H5Dset_extent(h->step_cell_off_dset,    t2_ext));
    H5_CHECK(H5Dset_extent(h->step_conn_id_off_dset, t2_ext));

    /* --- Fill buffers --- */
    static float p_buf[(NUM_TARGETS + 1) * 3];
    static float s_buf[NUM_TARGETS + 1];
    static float is_awacs_buf[NUM_TARGETS + 1];
    static float rcs_buf[NUM_TARGETS + 1];
    static float ad_buf[(NUM_TARGETS + 1) * 3];
    static float sd_buf[(NUM_TARGETS + 1) * 3];

    for (int i = 0; i < n; i++) {
        p_buf[i * 3 + 0] = targets[i].x_m;
        p_buf[i * 3 + 1] = targets[i].y_m;
        p_buf[i * 3 + 2] = targets[i].alt_m;
        s_buf[i] = (float)targets[i].tds;
        rcs_buf[i] = targets[i].rcs_now_m2;
        is_awacs_buf[i] = 0.0f;
        ad_buf[i * 3 + 0] = 0.0f; ad_buf[i * 3 + 1] = 0.0f; ad_buf[i * 3 + 2] = 0.0f;
        sd_buf[i * 3 + 0] = 0.0f; sd_buf[i * 3 + 1] = 0.0f; sd_buf[i * 3 + 2] = 0.0f;
    }

    p_buf[n * 3 + 0] = awacs->x;
    p_buf[n * 3 + 1] = awacs->y;
    p_buf[n * 3 + 2] = awacs->alt;
    s_buf[n] = 0.0f;
    rcs_buf[n] = 0.0f;   /* AWACS platform has no RCS in this context */
    is_awacs_buf[n] = 1.0f;
    ad_buf[n * 3 + 0] = cosf(awacs->dir);
    ad_buf[n * 3 + 1] = sinf(awacs->dir);
    ad_buf[n * 3 + 2] = 0.0f;

    const float rel_angle = sensor_dir - awacs->dir;
    const float fwd  = cosf(rel_angle);
    const float left = sinf(rel_angle) * cosf(awacs->rol);

    sd_buf[n * 3 + 0] = fwd * cosf(awacs->dir) - left * sinf(awacs->dir);
    sd_buf[n * 3 + 1] = fwd * sinf(awacs->dir) + left * cosf(awacs->dir);
    sd_buf[n * 3 + 2] = sinf(rel_angle) * sinf(awacs->rol);

    /* --- Write data hyperslabs --- */
    const hsize_t start_2d[2] = { h->current_step * total_pts, 0 };
    const hsize_t count_2d[2] = { (hsize_t)total_pts, 3 };
    const hid_t mspace_2d = H5Screate_simple(2, count_2d, NULL);

    hid_t fspace = H5Dget_space(h->pts_dset);
    H5_CHECK(fspace);
    H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, start_2d, NULL, count_2d, NULL));
    H5_CHECK(H5Dwrite(h->pts_dset, H5T_NATIVE_FLOAT, mspace_2d, fspace, H5P_DEFAULT, p_buf));
    H5_CHECK(H5Sclose(fspace));

    H5_CHECK(fspace = H5Dget_space(h->awacs_dir_dset));
    H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, start_2d, NULL, count_2d, NULL));
    H5_CHECK(H5Dwrite(h->awacs_dir_dset, H5T_NATIVE_FLOAT, mspace_2d, fspace, H5P_DEFAULT, ad_buf));
    H5_CHECK(H5Sclose(fspace));

    H5_CHECK(fspace = H5Dget_space(h->sensor_dir_dset));
    H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, start_2d, NULL, count_2d, NULL));
    H5_CHECK(H5Dwrite(h->sensor_dir_dset, H5T_NATIVE_FLOAT, mspace_2d, fspace, H5P_DEFAULT, sd_buf));
    H5_CHECK(H5Sclose(fspace));
    H5_CHECK(H5Sclose(mspace_2d));

    const hsize_t start_1d[1] = { h->current_step * total_pts };
    const hsize_t count_1d[1] = { (hsize_t)total_pts };
    const hid_t mspace_1d = H5Screate_simple(1, count_1d, NULL);

    H5_CHECK(fspace = H5Dget_space(h->status_dset));
    H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, start_1d, NULL, count_1d, NULL));
    H5_CHECK(H5Dwrite(h->status_dset, H5T_NATIVE_FLOAT, mspace_1d, fspace, H5P_DEFAULT, s_buf));
    H5_CHECK(H5Sclose(fspace));

    H5_CHECK(fspace = H5Dget_space(h->rcs_dset));
    H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, start_1d, NULL, count_1d, NULL));
    H5_CHECK(H5Dwrite(h->rcs_dset, H5T_NATIVE_FLOAT, mspace_1d, fspace, H5P_DEFAULT, rcs_buf));
    H5_CHECK(H5Sclose(fspace));

    H5_CHECK(fspace = H5Dget_space(h->is_awacs_dset));
    H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, start_1d, NULL, count_1d, NULL));
    H5_CHECK(H5Dwrite(h->is_awacs_dset, H5T_NATIVE_FLOAT, mspace_1d, fspace, H5P_DEFAULT, is_awacs_buf));
    H5_CHECK(H5Sclose(fspace));
    H5_CHECK(H5Sclose(mspace_1d));

    /* --- Write temporal metadata --- */
    const hsize_t t_start[1] = { h->current_step };
    const hsize_t t_count[1] = { 1 };

    const int64_t pts_off = (int64_t)(h->current_step * total_pts);
    const int64_t part_off = 0;
    const int64_t num_parts = 1;

    const hid_t t_mspace = H5Screate_simple(1, t_count, NULL);
    H5_CHECK(t_mspace);

    #define WRITE_STEP_DATA(dset, val_ptr, type) do { \
                fspace = H5Dget_space(dset); \
                H5Sselect_hyperslab(fspace, H5S_SELECT_SET, t_start, NULL, t_count, NULL); \
                H5Dwrite(dset, type, t_mspace, fspace, H5P_DEFAULT, val_ptr); \
                H5Sclose(fspace); \
        } while(0)

    WRITE_STEP_DATA(h->step_vals_dset, &time_val, H5T_NATIVE_FLOAT);
    WRITE_STEP_DATA(h->step_pts_off_dset, &pts_off, H5T_NATIVE_INT64);
    WRITE_STEP_DATA(h->step_part_off_dset, &part_off, H5T_NATIVE_INT64);
    WRITE_STEP_DATA(h->step_num_parts_dset, &num_parts, H5T_NATIVE_INT64);

    #undef WRITE_STEP_DATA
    H5_CHECK(H5Sclose(t_mspace));

    const int64_t cell_off_row[5]    = { 0, 0, 0, 0, 0 };
    const int64_t conn_id_off_row[5] = { 0, 0, 0, 0, 0 };
    const hsize_t t2_start[2] = { h->current_step, 0 };
    const hsize_t t2_count[2] = { 1, 5 };
    const hid_t t2_mspace = H5Screate_simple(2, t2_count, NULL);
    H5_CHECK(t2_mspace);

    #define WRITE_STEP_DATA_2D(dset, val_ptr) do { \
            fspace = H5Dget_space(dset); \
            H5_CHECK(fspace); \
            H5_CHECK(H5Sselect_hyperslab(fspace, H5S_SELECT_SET, t2_start, NULL, t2_count, NULL)); \
            H5_CHECK(H5Dwrite(dset, H5T_NATIVE_INT64, t2_mspace, fspace, H5P_DEFAULT, val_ptr)); \
            H5_CHECK(H5Sclose(fspace)); \
        } while(0)

    WRITE_STEP_DATA_2D(h->step_cell_off_dset,    cell_off_row);
    WRITE_STEP_DATA_2D(h->step_conn_id_off_dset, conn_id_off_row);

    #undef WRITE_STEP_DATA_2D
    H5_CHECK(H5Sclose(t2_mspace));

    h->current_step++;
}

void events_vtkhdf_close(const struct vtkhdf_handle *const h)
{
    const hid_t st_group = H5Gopen2(h->file_id, "VTKHDF/Steps", H5P_DEFAULT);
    H5_CHECK(st_group);

    const hid_t s_space = H5Screate(H5S_SCALAR);
    H5_CHECK(s_space);
    const hid_t attr = H5Acreate2(st_group, "NSteps", H5T_NATIVE_UINT64, s_space, H5P_DEFAULT, H5P_DEFAULT);
    H5_CHECK(attr);
    H5_CHECK(H5Awrite(attr, H5T_NATIVE_UINT64, &h->current_step));

    H5_CHECK(H5Aclose(attr));
    H5_CHECK(H5Sclose(s_space));
    H5_CHECK(H5Gclose(st_group));

    const hid_t root = H5Gopen2(h->file_id, "VTKHDF", H5P_DEFAULT);
    H5_CHECK(root);
    write_dummy_topology_stepped(root, "Lines",    h->current_step);
    write_dummy_topology_stepped(root, "Polygons", h->current_step);
    write_dummy_topology_stepped(root, "Strips",   h->current_step);
    H5_CHECK(H5Gclose(root));

    H5_CHECK(H5Dclose(h->pts_dset));
    H5_CHECK(H5Dclose(h->status_dset));
    H5_CHECK(H5Dclose(h->rcs_dset));
    H5_CHECK(H5Dclose(h->is_awacs_dset));
    H5_CHECK(H5Dclose(h->awacs_dir_dset));
    H5_CHECK(H5Dclose(h->sensor_dir_dset));
    H5_CHECK(H5Dclose(h->step_vals_dset));
    H5_CHECK(H5Dclose(h->step_pts_off_dset));
    H5_CHECK(H5Dclose(h->step_cell_off_dset));
    H5_CHECK(H5Dclose(h->step_part_off_dset));
    H5_CHECK(H5Dclose(h->step_num_parts_dset));
    H5_CHECK(H5Dclose(h->step_conn_id_off_dset));

    H5_CHECK(H5Fclose(h->file_id));
}

/* Export the racetrack orbit as a 3D line loop for ParaView (.vtp) */
void racetrack_write_vtp(const struct racetrack *rt, const char *filename)
{
    const unsigned int npoints = 500u;

    FILE *fp = fopen(filename, "w");
    if (!fp) {
        fprintf(stderr, "Failed to open %s for writing.\n", filename);
        return;
    }

    fprintf(fp, "<?xml version=\"1.0\"?>\n");
    fprintf(fp, "<VTKFile type=\"PolyData\" version=\"0.1\" byte_order=\"LittleEndian\">\n");
    fprintf(fp, "  <PolyData>\n");
    fprintf(fp, "    <Piece NumberOfPoints=\"%d\" NumberOfLines=\"1\">\n", npoints);
    fprintf(fp, "      <Points>\n");
    fprintf(fp, "        <DataArray type=\"Float32\" NumberOfComponents=\"3\" format=\"ascii\">\n");

    struct platform_state st;
    const float tstep = rt->orbit_time_s / (float)npoints;

    for (unsigned int i = 0; i < npoints; i++) {
        const float t = rt->start_time + ((float)i * tstep);
        /* Abusing the platform state calculator to get point coordinates */
        platform_state_update(&st, rt, t);
        fprintf(fp, "          %.2f %.2f %.2f\n", st.x, st.y, st.alt);
    }

    fprintf(fp, "        </DataArray>\n");
    fprintf(fp, "      </Points>\n");
    fprintf(fp, "      <Lines>\n");
    fprintf(fp, "        <DataArray type=\"Int32\" Name=\"connectivity\" format=\"ascii\">\n");
    fprintf(fp, "          ");
    for (unsigned int i = 0; i < npoints; i++) {
        fprintf(fp, "%d ", i);
    }

    fprintf(fp, "0\n");
    fprintf(fp, "        </DataArray>\n");
    fprintf(fp, "        <DataArray type=\"Int32\" Name=\"offsets\" format=\"ascii\">\n");
    fprintf(fp, "          %d\n", npoints + 1);
    fprintf(fp, "        </DataArray>\n");
    fprintf(fp, "      </Lines>\n");
    fprintf(fp, "      <PointData>\n");
    fprintf(fp, "        <DataArray type=\"Float32\" Name=\"Roll_Angle\" format=\"ascii\">\n");
    for (unsigned int i = 0; i < npoints; i++) {
        platform_state_update(&st, rt, rt->start_time + (float)i * tstep);
        fprintf(fp, "          %.4f\n", st.rol * (180.0 / M_PI));
    }

    fprintf(fp, "        </DataArray>\n");
    fprintf(fp, "      </PointData>\n");
    fprintf(fp, "    </Piece>\n");
    fprintf(fp, "  </PolyData>\n");
    fprintf(fp, "</VTKFile>\n");

    fclose(fp);
}
