# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - doxygen

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
